Options:
  DFTBPlusHSD: "dftb_in.hsd"
  DFTBPlusPath: "dftb+"
Testsets:
  G2/97:
    path: "G2_97"
    type: "atomization"
    references:
      c1h1n1_hydrogencyanide: 313.3
      c1h2_methylene: 181.6
      c1h2o1_formaldehyde: 374.4
      c1h2o2_formicacid: 500.9
      c1h3n1_methanimine: 438.5
      c1h3n1o2_methylnitrite: 598.5
      c1h3n1o2_nitromethane: 601.1
      c1h4_methane: 419.7
      c1h4o1_methanol: 512.1
      c1h5n1_methylamine: 580.5
      c1o1_carbonmonoxide: 259.8
      c1o2_carbondioxide: 390.6
      c2h2_ethyne: 404.9
      c2h2o1_ketene: 533.0
      c2h2o2_glyoxal: 634.5
      c2h3n1_acetonitrile: 616.0
      c2h4_ethene: 563.0
      c2h4o1_acetaldehyde: 675.5
      c2h4o1_oxirane: 650.0
      c2h4o2_aceticacid: 802.2
      c2h4o2_methylformate: 785.9
      c2h5n1_aziridine: 718.1
      c2h5n1o1_acetamide: 866.5
      c2h6_ethane: 711.4
      c2h6o1_dimethylether: 797.3
      c2h6o1_ethanol: 809.2
      c2h7n1_dimethylamine: 868.4
      c2h7n1_ethylamine: 876.2
      c2n2_cyanogen: 503.4
      c3h3n1_acrylonitrile: 762.5
      c3h4_allene: 703.1
      c3h4_cyclopropene: 680.0
      c3h4_propyne: 704.3
      c3h6_cyclopropane: 851.5
      c3h6o1_acetone: 977.5
      c3h6_propene: 859.6
      c3h8o1_isopropanol: 1107.2
      c3h8o1_methylethylether: 1094.6
      c3h8_propane: 1005.3
      c3h9n1_trimethylamine: 1159.2
      c4h10_butane: 1299.4
      c4h10_isobutane: 1301.0
      c4h4o1_furan: 992.8
      c4h5n1_pyrrole: 1069.8
      c4h6_13butadiene: 1011.2
      c4h6_2butyne: 1002.8
      c4h6_bicyclobutane: 983.6
      c4h6_cyclobutene: 998.7
      c4h6_methylenecyclopropane: 991.3
      c4h8_cyclobutane: 1147.2
      c4h8_isobutene: 1157.1
      c5h5n1_pyridine: 1236.7
      c5h8_spiropentane: 1282.4
      c6h6_benzene: 1365.9
      h1n1o2_nitrousacid: 311.3
      h1n1o3_nitricacid: 387.5
      h2_hydrogen: 109.8
      h2n2_transdiazene: 295.4
      h2o1_water: 231.9
      h2o2_hydrogenperoxide: 267.5
      h3n1_ammonia: 296.8
      h4n2_hydrazine: 436.1
      n2_nitrogen: 227.8
      n2o1_nitrousoxide: 270.8
      o2_oxygen1: 91.4
